const {
  SlashCommandBuilder, EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle,
  StringSelectMenuBuilder, ModalBuilder, TextInputBuilder, TextInputStyle,
  ChannelType, PermissionFlagsBits, AttachmentBuilder
} = require('discord.js');
const fs = require('fs');

const commands = [
  new SlashCommandBuilder().setName('ping').setDescription('Verifica o bot.'),
  new SlashCommandBuilder().setName('ajuda').setDescription('Mostra todos os comandos.'),
  new SlashCommandBuilder().setName('painel').setDescription('Abre o painel administrativo.'),
  new SlashCommandBuilder().setName('configurar').setDescription('Abre o menu de configuração.'),
  new SlashCommandBuilder().setName('configurarcanal').setDescription('Configura canal/categoria de tickets ou logs.')
    .addStringOption(o=>o.setName('tipo').setDescription('O que configurar').setRequired(true).addChoices({name:'Logs',value:'logs'},{name:'Categoria de tickets',value:'categoria'}))
    .addChannelOption(o=>o.setName('canal').setDescription('Canal ou categoria').setRequired(true)),
  new SlashCommandBuilder().setName('configurarlogs').setDescription('Configura o canal de logs.').addChannelOption(o=>o.setName('canal').setDescription('Canal').addChannelTypes(ChannelType.GuildText).setRequired(true)),
  new SlashCommandBuilder().setName('configurarstaff').setDescription('Configura o cargo da staff.').addRoleOption(o=>o.setName('cargo').setDescription('Cargo').setRequired(true)),
  new SlashCommandBuilder().setName('produtos').setDescription('Mostra os produtos.'),
  new SlashCommandBuilder().setName('estoque').setDescription('Consulta o estoque.').addStringOption(o=>o.setName('produto').setDescription('Produto').setRequired(true)),
  new SlashCommandBuilder().setName('configurarproduto').setDescription('Cria/configura um produto.').addStringOption(o=>o.setName('nome').setDescription('Nome').setRequired(true)).addNumberOption(o=>o.setName('preco').setDescription('Preço').setMinValue(0).setRequired(true)).addStringOption(o=>o.setName('descricao').setDescription('Descrição').setRequired(false)),
  new SlashCommandBuilder().setName('editarproduto').setDescription('Edita um produto.').addStringOption(o=>o.setName('produto').setDescription('Produto').setRequired(true)).addNumberOption(o=>o.setName('preco').setDescription('Novo preço').setMinValue(0).setRequired(false)).addStringOption(o=>o.setName('descricao').setDescription('Nova descrição').setRequired(false)),
  new SlashCommandBuilder().setName('reestock').setDescription('Adiciona unidades ao estoque.').addStringOption(o=>o.setName('produto').setDescription('Produto').setRequired(true)).addStringOption(o=>o.setName('itens').setDescription('Itens separados por |').setRequired(true)),
  new SlashCommandBuilder().setName('removerestoque').setDescription('Remove unidades do estoque.').addStringOption(o=>o.setName('produto').setDescription('Produto').setRequired(true)).addIntegerOption(o=>o.setName('quantidade').setDescription('Quantidade').setMinValue(1).setRequired(true)),
  new SlashCommandBuilder().setName('painel-ticket').setDescription('Publica o painel de compra.'),
  new SlashCommandBuilder().setName('ticket').setDescription('Abre um ticket de suporte.'),
  new SlashCommandBuilder().setName('fecharticket').setDescription('Fecha o ticket atual.'),
  new SlashCommandBuilder().setName('addticket').setDescription('Adiciona alguém ao ticket.').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)),
  new SlashCommandBuilder().setName('removeticket').setDescription('Remove alguém do ticket.').addUserOption(o=>o.setName('usuario').setDescription('Usuário').setRequired(true)),
  new SlashCommandBuilder().setName('avaliar').setDescription('Avalia uma compra.').addIntegerOption(o=>o.setName('nota').setDescription('1 a 5').setMinValue(1).setMaxValue(5).setRequired(true)).addStringOption(o=>o.setName('comentario').setDescription('Comentário').setRequired(false)),
  new SlashCommandBuilder().setName('avaliacoes').setDescription('Mostra avaliações.'),
  new SlashCommandBuilder().setName('feedback').setDescription('Configura/exibe o sistema de feedback.'),
  new SlashCommandBuilder().setName('configurarpix').setDescription('Configura PIX/PicPay.').addStringOption(o=>o.setName('dados').setDescription('Chave e instruções').setRequired(true)),
  new SlashCommandBuilder().setName('pix').setDescription('Mostra o PIX configurado.'),
  new SlashCommandBuilder().setName('pagamentos').setDescription('Mostra estatísticas de pagamentos.'),
  new SlashCommandBuilder().setName('confirmarpagamento').setDescription('Confirma pagamento do ticket.').addStringOption(o=>o.setName('observacao').setDescription('Observação opcional').setRequired(false)),
  new SlashCommandBuilder().setName('configurarentrega').setDescription('Configura a entrega.').addStringOption(o=>o.setName('modo').setDescription('Modo').setRequired(true).addChoices({name:'No ticket',value:'ticket'},{name:'DM automática',value:'dm'},{name:'Manual',value:'manual'})),
  new SlashCommandBuilder().setName('entrega').setDescription('Entrega o produto do ticket.').addStringOption(o=>o.setName('produto').setDescription('Produto').setRequired(false)),
  new SlashCommandBuilder().setName('reestockauto').setDescription('Configura alerta de estoque baixo.').addIntegerOption(o=>o.setName('limite').setDescription('Limite de alerta').setMinValue(0).setRequired(false)),
  new SlashCommandBuilder().setName('backup').setDescription('Gera backup dos dados.'),
  new SlashCommandBuilder().setName('manutencao').setDescription('Liga/desliga manutenção.').addBooleanOption(o=>o.setName('ativar').setDescription('Ativar').setRequired(true)),
];

const embed = (title, description) => new EmbedBuilder().setTitle(title).setDescription(description).setTimestamp();
const isAdmin = i => i.memberPermissions?.has(PermissionFlagsBits.Administrator);
async function log(guild, g, text) { if (!g.settings.logsChannelId) return; const ch=guild.channels.cache.get(g.settings.logsChannelId); if(ch?.isTextBased()) await ch.send({content:text}).catch(()=>{}); }
async function refreshPanels(guild, g) {
  const rows = Object.values(g.products).filter(p=>p.active !== false).slice(0,25);
  const menu = rows.length ? new StringSelectMenuBuilder().setCustomId('alpha_buy_select').setPlaceholder('🛒 Selecione um produto').addOptions(rows.map(p=>({label:p.name.slice(0,100),description:`${money(p.price)} • ${p.stock.length} unidade(s)`.slice(0,100),value:p.id}))) : null;
  const components = menu ? [new ActionRowBuilder().addComponents(menu)] : [];
  const e=embed('⚡ ALPHA BOT • CENTRAL DE COMPRAS', rows.length ? 'Selecione um produto abaixo para abrir seu pedido privado.\n\n📦 Estoque em tempo real\n💳 Pagamento configurado\n🎫 Ticket privado\n📩 Entrega após confirmação' : '📦 Nenhum produto disponível no momento.');
  for (const pm of (g.settings.panelMessages||[])) { const ch=guild.channels.cache.get(pm.channelId); if(!ch) continue; const m=await ch.messages.fetch(pm.messageId).catch(()=>null); if(m) await m.edit({embeds:[e],components}).catch(()=>{}); }
}
async function createTicket(i, g, product, support=false) {
  const existing=Object.values(g.tickets).find(t=>t.userId===i.user.id && t.status!=='closed');
  if(existing){const ch=i.guild.channels.cache.get(existing.channelId); if(ch) return ch;}
  const ch=await i.guild.channels.create({name:`ticket-${i.user.username}`.toLowerCase().replace(/[^a-z0-9-]/g,'-').slice(0,90),type:ChannelType.GuildText,parent:g.settings.ticketCategoryId||undefined,permissionOverwrites:[{id:i.guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:i.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]},...(g.settings.staffRoleId?[{id:g.settings.staffRoleId,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages,PermissionFlagsBits.ReadMessageHistory]}]:[])]});
  const order=++g.counters.order; const orderId=`ALPHA-${String(order).padStart(5,'0')}`;
  g.orders[orderId]={id:orderId,userId:i.user.id,productId:product?.id||null,price:product?.price||0,status:product?'awaiting_payment':'support',ticketChannelId:ch.id,createdAt:new Date().toISOString()};
  g.tickets[ch.id]={channelId:ch.id,userId:i.user.id,productId:product?.id||null,orderId,status:'open',createdAt:new Date().toISOString()};
  const e=embed(`🎫 PEDIDO ${orderId}`, product ? `📦 **Produto:** ${product.name}\n💰 **Valor:** ${money(product.price)}\n📊 **Estoque:** ${product.stock.length} unidade(s)\n\n💳 Clique em **Pagamento** para ver o PIX/PicPay configurado.\n📸 Após pagar, envie o comprovante neste ticket.\n\n🔐 Seu pedido está vinculado a este ticket.` : '👋 Explique aqui como podemos ajudar.');
  const buttons=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('alpha_pay').setLabel('💳 Pagamento').setStyle(ButtonStyle.Success),new ButtonBuilder().setCustomId('alpha_close').setLabel('🔒 Fechar').setStyle(ButtonStyle.Danger));
  await ch.send({content:`<@${i.user.id}>`,embeds:[e],components:[buttons]});
  await log(i.guild,g,`🎫 Ticket criado • ${orderId} • <@${i.user.id}>${product?` • ${product.name}`:''}`);
  return ch;
}

async function handleCommand(i, ctx) {
  const g=ctx.gid(i.guildId), c=i.commandName;
  if(c==='ping') return i.reply('🏓 **Pong!** Alpha Bot V5 está online.');
  if(c==='ajuda') return i.reply({ephemeral:true,embeds:[embed('⚡ ALPHA BOT V5 • COMANDOS','**🛒 Loja**\n`/produtos` `/estoque` `/configurarproduto` `/editarproduto` `/reestock` `/removerestoque`\n\n**🎫 Tickets**\n`/painel-ticket` `/ticket` `/fecharticket` `/addticket` `/removeticket`\n\n**💳 Pagamentos**\n`/configurarpix` `/pix` `/pagamentos` `/confirmarpagamento`\n\n**📦 Entrega**\n`/configurarentrega` `/entrega` `/reestockauto`\n\n**⚙️ Administração**\n`/painel` `/configurar` `/configurarcanal` `/configurarlogs` `/configurarstaff` `/backup` `/manutencao`\n\n**⭐ Pós-venda**\n`/avaliar` `/avaliacoes` `/feedback`') ]});
  if(['configurar','configurarcanal','configurarlogs','configurarstaff','configurarpix','configurarproduto','editarproduto','reestock','removerestoque','painel-ticket','pagamentos','confirmarpagamento','configurarentrega','entrega','reestockauto','backup','manutencao'].includes(c) && !(await ctx.staffOnly(i))) return;
  if(c==='painel'||c==='configurar') return i.reply({ephemeral:true,embeds:[embed('⚙️ ALPHA BOT • CONFIGURAÇÃO',`👥 Staff: ${g.settings.staffRoleId?`<@&${g.settings.staffRoleId}>`:'não configurada'}\n📋 Logs: ${g.settings.logsChannelId?`<#${g.settings.logsChannelId}>`:'não configurado'}\n🎫 Categoria: ${g.settings.ticketCategoryId?`<#${g.settings.ticketCategoryId}>`:'não configurada'}\n💳 PIX: ${g.settings.pix?'✅ configurado':'❌ não configurado'}\n📦 Entrega: **${g.settings.deliveryMode}**\n🔧 Manutenção: **${g.settings.maintenance?'ATIVA':'OFF'}**\n🚨 Limite de estoque: **${g.settings.lowStockThreshold}**`) ]});
  if(c==='configurarcanal'){const tipo=i.options.getString('tipo'), ch=i.options.getChannel('canal'); if(tipo==='logs'){g.settings.logsChannelId=ch.id;} else {g.settings.ticketCategoryId=ch.id;} ctx.saveDB(); return i.reply({content:'✅ Configuração salva.',ephemeral:true});}
  if(c==='configurarlogs'){g.settings.logsChannelId=i.options.getChannel('canal').id;ctx.saveDB();return i.reply({content:'✅ Canal de logs configurado.',ephemeral:true});}
  if(c==='configurarstaff'){g.settings.staffRoleId=i.options.getRole('cargo').id;ctx.saveDB();return i.reply({content:'✅ Cargo da staff configurado.',ephemeral:true});}
  if(c==='configurarpix'){g.settings.pix=i.options.getString('dados');ctx.saveDB();return i.reply({content:'✅ PIX/PicPay configurado. Ele aparecerá nos tickets.',ephemeral:true});}
  if(c==='configurarproduto'){const name=i.options.getString('nome'), id=ctx.idify(name); const old=g.products[id]; g.products[id]={id,name,price:i.options.getNumber('preco'),description:i.options.getString('descricao')||'',stock:old?.stock||[],sold:old?.sold||0,totalRestocked:old?.totalRestocked||0,active:true,createdAt:old?.createdAt||ctx.stamp(),updatedAt:ctx.stamp()};ctx.audit(g,i.user.id,'produto_criado_ou_atualizado',name);return i.reply({content:`✅ Produto **${name}** configurado.\n🆔 ID: \`${id}\`\n📦 Estoque: **${g.products[id].stock.length}**\nUse \`/reestock\` para adicionar unidades.`,ephemeral:true});}
  if(c==='editarproduto'){const p=ctx.product(g,i.options.getString('produto'));if(!p)return i.reply({content:'❌ Produto não encontrado.',ephemeral:true});const price=i.options.getNumber('preco'),desc=i.options.getString('descricao');if(price!==null)p.price=price;if(desc!==null)p.description=desc;p.updatedAt=ctx.stamp();ctx.saveDB();await refreshPanels(i.guild,g);return i.reply({content:'✅ Produto atualizado.',ephemeral:true});}
  if(c==='produtos'){const ps=Object.values(g.products).filter(p=>p.active!==false);if(!ps.length)return i.reply('📦 Nenhum produto cadastrado.');return i.reply({embeds:[embed('🛍️ ALPHA BOT • PRODUTOS',ps.slice(0,25).map(p=>`**${p.name}**\n💰 ${money(p.price)} • 📦 ${p.stock.length} unidade(s)\n${p.description||'Sem descrição.'}\n🆔 \`${p.id}\``).join('\n\n'))]});}
  if(c==='estoque'){const p=ctx.product(g,i.options.getString('produto'));if(!p)return i.reply('❌ Produto não encontrado.');return i.reply({embeds:[embed(`📦 ESTOQUE • ${p.name}`,`📊 **Atual:** ${p.stock.length}\n🛒 **Vendidos:** ${p.sold}\n🔄 **Total reposto:** ${p.totalRestocked}\n🆔 **ID:** \`${p.id}\`\n🚦 **Status:** ${p.stock.length?'🟢 DISPONÍVEL':'🔴 ESGOTADO'}`)]});}
  if(c==='reestock'){const p=ctx.product(g,i.options.getString('produto'));if(!p)return i.reply({content:'❌ Produto não encontrado.',ephemeral:true});const before=p.stock.length,items=i.options.getString('itens').split('|').map(x=>x.trim()).filter(Boolean);p.stock.push(...items);p.totalRestocked+=items.length;p.updatedAt=ctx.stamp();const wasEmpty=before===0;ctx.audit(g,i.user.id,'reestock',`${p.name}: +${items.length}`);await refreshPanels(i.guild,g);await log(i.guild,g,`📦 **REESTOCK**\nProduto: **${p.name}**\n➕ Adicionado: **+${items.length}**\n📊 Estoque: **${before} → ${p.stock.length}**\n👤 Reposto por: <@${i.user.id}>\n🆔 ID: \`${p.id}\`${wasEmpty?'\n🚨 Estava esgotado e voltou ao estoque.':''}`);return i.reply({embeds:[embed('📦 ALPHA BOT • PRODUTO REABASTECIDO',`📦 **Produto:** ${p.name}\n➕ **Quantidade adicionada:** +${items.length}\n📊 **Estoque atual:** ${p.stock.length} unidade(s)\n👤 **Reposto por:** <@${i.user.id}>\n🛒 **Canal:** ${i.channel}\n🆔 **ID do produto:** \`${p.id}\`${wasEmpty?'\n\n🚨 *Este produto estava **ESGOTADO** e voltou ao estoque.*':''}`)]});}
  if(c==='removerestoque'){const p=ctx.product(g,i.options.getString('produto'));if(!p)return i.reply({content:'❌ Produto não encontrado.',ephemeral:true});const before=p.stock.length,q=Math.min(i.options.getInteger('quantidade'),before);p.stock.splice(-q,q);ctx.saveDB();await refreshPanels(i.guild,g);return i.reply({content:`✅ Removidas **${q}** unidade(s). Estoque: **${before} → ${p.stock.length}**.`,ephemeral:true});}
  if(c==='painel-ticket'){const e=embed('⚡ ALPHA BOT • CENTRAL DE COMPRAS','Selecione abaixo o produto que deseja comprar.\n\n🔒 Ticket privado\n💳 PIX/PicPay\n📸 Comprovante\n✅ Confirmação pela staff\n📦 Entrega integrada ao estoque');const ps=Object.values(g.products).filter(p=>p.active!==false).slice(0,25);const menu=ps.length?new StringSelectMenuBuilder().setCustomId('alpha_buy_select').setPlaceholder('🛒 Escolha seu produto').addOptions(ps.map(p=>({label:p.name.slice(0,100),description:`${money(p.price)} • ${p.stock.length} em estoque`.slice(0,100),value:p.id}))):null;const msg=await i.channel.send({embeds:[e],components:menu?[new ActionRowBuilder().addComponents(menu)]:[]});g.settings.panelMessages.push({channelId:i.channel.id,messageId:msg.id});ctx.saveDB();return i.reply({content:'✅ Painel publicado e vinculado ao estoque.',ephemeral:true});}
  if(c==='ticket'){const ch=await createTicket(i,g,null,true);return i.reply({content:`🎫 Ticket criado: ${ch}`,ephemeral:true});}
  if(c==='fecharticket'){const t=ctx.currentTicket(g,i.channel.id);if(!t)return i.reply({content:'❌ Este canal não é um ticket.',ephemeral:true});await i.reply('🔒 Fechando ticket...');t.status='closed';ctx.saveDB();await log(i.guild,g,`🔒 Ticket fechado • ${t.orderId||'suporte'} • por <@${i.user.id}>`);setTimeout(()=>i.channel.delete().catch(()=>{}),1200);return;}
  if(c==='addticket'||c==='removeticket'){const t=ctx.currentTicket(g,i.channel.id);if(!t)return i.reply({content:'❌ Use dentro de um ticket.',ephemeral:true});const u=i.options.getUser('usuario');if(c==='addticket')await i.channel.permissionOverwrites.edit(u.id,{ViewChannel:true,SendMessages:true,ReadMessageHistory:true});else await i.channel.permissionOverwrites.delete(u.id).catch(()=>{});return i.reply(`✅ ${u} ${c==='addticket'?'adicionado ao':'removido do'} ticket.`);}
  if(c==='avaliar'){if(i.options.getInteger('nota')<1||i.options.getInteger('nota')>5)return i.reply({content:'❌ Nota inválida.',ephemeral:true});g.reviews.unshift({userId:i.user.id,rating:i.options.getInteger('nota'),comment:i.options.getString('comentario')||'',at:ctx.stamp()});g.reviews=g.reviews.slice(0,200);ctx.saveDB();return i.reply('⭐ Obrigado pela avaliação!');}
  if(c==='avaliacoes'){if(!g.reviews.length)return i.reply('⭐ Ainda não há avaliações.');const avg=g.reviews.reduce((a,r)=>a+r.rating,0)/g.reviews.length;return i.reply({embeds:[embed('⭐ ALPHA BOT • AVALIAÇÕES',`⭐ Média: **${avg.toFixed(1)}/5**\n📊 Total: **${g.reviews.length}**\n\n${g.reviews.slice(0,8).map(r=>`<@${r.userId}> — ${'⭐'.repeat(r.rating)}${r.comment?`\n> ${r.comment}`:''}`).join('\n\n')}`)]});}
  if(c==='feedback')return i.reply({ephemeral:true,content:`⭐ Feedback automático: **${g.settings.feedbackEnabled?'ATIVADO':'DESATIVADO'}**\nUse o sistema de avaliação após as entregas.`});
  if(c==='pix')return i.reply(g.settings.pix?{embeds:[embed('💳 PAGAMENTO PIX / PICPAY',g.settings.pix)]}:'❌ O PIX ainda não foi configurado.');
  if(c==='pagamentos'){const total=g.sales.reduce((a,s)=>a+s.price,0);return i.reply({ephemeral:true,embeds:[embed('💰 ALPHA BOT • PAGAMENTOS',`🛒 Vendas: **${g.sales.length}**\n💵 Faturamento registrado: **${money(total)}**\n📦 Itens entregues: **${g.sales.length}**`)]});}
  if(c==='confirmarpagamento'){const t=ctx.currentTicket(g,i.channel.id);if(!t||!t.productId)return i.reply({content:'❌ Ticket sem produto associado.',ephemeral:true});const p=ctx.product(g,t.productId);if(!p||!p.stock.length)return i.reply({content:'❌ Sem estoque para este produto.',ephemeral:true});const order=g.orders[t.orderId];if(order?.status==='paid'||order?.status==='delivered')return i.reply({content:'⚠️ Este pedido já foi confirmado.',ephemeral:true});const item=p.stock.shift();p.sold++;const sale=++g.counters.sale;const saleId=`VENDA-${String(sale).padStart(5,'0')}`;const buyer=t.userId;g.sales.unshift({id:saleId,orderId:t.orderId,userId:buyer,productId:p.id,productName:p.name,price:p.price,item,confirmedBy:i.user.id,at:ctx.stamp()});if(order){order.status='paid';order.saleId=saleId;order.paidAt=ctx.stamp();}t.status='paid';ctx.saveDB();await refreshPanels(i.guild,g);await log(i.guild,g,`💰 **VENDA CONFIRMADA**\n🆔 ${saleId}\n📦 ${p.name}\n💵 ${money(p.price)}\n👤 Cliente: <@${buyer}>\n👮 Staff: <@${i.user.id}>\n📉 Estoque: ${p.stock.length}`);const mode=g.settings.deliveryMode;if(mode==='dm'){const u=await i.client.users.fetch(buyer).catch(()=>null);if(u)await u.send(`📦 **Sua entrega - ${p.name}**\n\n\`${item}\`\n\n🆔 Pedido: ${t.orderId}`).then(()=>true).catch(()=>false);t.status='delivered';if(order)order.status='delivered';ctx.saveDB();return i.reply(`✅ Pagamento confirmado.\n📦 Entrega enviada por DM.\n📉 Estoque: **${p.stock.length}**`);}if(mode==='ticket'){t.deliveredItem=item;t.status='delivered';if(order)order.status='delivered';ctx.saveDB();return i.reply(`✅ Pagamento confirmado.\n📦 **Entrega:**\n\`\`\`\n${item}\n\`\`\`\n📉 Estoque: **${p.stock.length}**`);}t.deliveredItem=item;ctx.saveDB();return i.reply(`✅ Pagamento confirmado e registrado.\n📦 Use \`/entrega\` para entregar o item.\n📉 Estoque: **${p.stock.length}**`);}
  if(c==='configurarentrega'){g.settings.deliveryMode=i.options.getString('modo');ctx.saveDB();return i.reply({content:`✅ Modo de entrega definido: **${g.settings.deliveryMode}**.`,ephemeral:true});}
  if(c==='entrega'){const t=ctx.currentTicket(g,i.channel.id);if(!t||!t.productId)return i.reply({content:'❌ Ticket sem produto.',ephemeral:true});if(t.deliveredItem)return i.reply(`📦 Entrega já separada:\n\`\`\`\n${t.deliveredItem}\n\`\`\``);const p=ctx.product(g,i.options.getString('produto')||t.productId);if(!p||!p.stock.length)return i.reply({content:'❌ Produto sem estoque.',ephemeral:true});const item=p.stock.shift();p.sold++;t.deliveredItem=item;t.status='delivered';ctx.saveDB();return i.reply(`📦 Entrega:\n\`\`\`\n${item}\n\`\`\`\n📉 Estoque restante: **${p.stock.length}**`);}
  if(c==='reestockauto'){const lim=i.options.getInteger('limite');if(lim!==null)g.settings.lowStockThreshold=lim;ctx.saveDB();return i.reply({ephemeral:true,content:`🚨 Alerta de estoque baixo configurado para **${g.settings.lowStockThreshold}** unidade(s).\n\nA V5 detecta estoque baixo após alterações; reposição real continua sendo feita com \`/reestock\`.`});}
  if(c==='backup'){ctx.saveNow();const name=`alpha-backup-${Date.now()}.json`;const file=`${ctx.backupDir}/${name}`;fs.copyFileSync(ctx.dbFile,file);return i.reply({content:'✅ Backup criado.',files:[new AttachmentBuilder(file,{name})],ephemeral:true});}
  if(c==='manutencao'){g.settings.maintenance=i.options.getBoolean('ativar');ctx.saveDB();return i.reply({content:g.settings.maintenance?'🔧 **MODO MANUTENÇÃO ATIVADO.** Compras bloqueadas.':'✅ **LOJA REABERTA.**',ephemeral:true});}
}

async function handleButton(i,ctx){const g=ctx.gid(i.guildId);if(i.customId==='alpha_pay')return i.reply({ephemeral:true,content:g.settings.pix?`💳 **PIX/PicPay**\n\n${g.settings.pix}\n\n📸 Pague e envie o comprovante neste ticket.`:'❌ O pagamento ainda não foi configurado.'});if(i.customId==='alpha_close'){const t=ctx.currentTicket(g,i.channel.id);if(!t)return i.reply({content:'❌ Ticket inválido.',ephemeral:true});t.status='closed';ctx.saveDB();await i.reply('🔒 Fechando ticket...');setTimeout(()=>i.channel.delete().catch(()=>{}),1200);}}
async function handleSelect(i,ctx){const g=ctx.gid(i.guildId);if(i.customId!=='alpha_buy_select')return;const p=ctx.product(g,i.values[0]);if(!p)return i.update({content:'❌ Produto não encontrado.',components:[]});if(g.settings.maintenance&&!ctx.staff(i))return i.update({content:'🔧 A loja está em manutenção.',components:[]});if(!p.stock.length)return i.update({content:'❌ Este produto está esgotado.',components:[]});const ch=await createTicket(i,g,p);return i.update({content:`✅ Seu pedido foi criado: ${ch}`,components:[]});}
async function handleModal(){ }
module.exports={commands,handleCommand,handleButton,handleSelect,handleModal};
